name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: php:8.2-cli-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apk add --no-cache composer
          composer install --no-interaction --no-progress
      - name: Run PHPUnit
        run: vendor/bin/phpunit
